#!/usr/bin/env ruby
# Usage: md2review [--parse-<extension>...] [--render-<extension>...] [<file>...]
#
# Convert one or more Markdown files to Re:VIEW and write to standard output. With
# no <file> or when <file> is '-', read Markdown source text from standard input.
# With <extension>s, perform additional Markdown processing before writing output.

require "md2starter"
require "md2starter/version"

if ARGV.include?("--help")
  File.read(__FILE__).split("\n").grep(/^# /).each do |line|
    puts line[2..-1]
  end
  exit 0
end
